### ISSUE TITLE
Feature Request 4GB Patch

### ISSUE THREAD

**Issue by SSDDX-Devs** [namreeb/wowreeb#18]
Hello Sir
Firstly i want to thank you for your work 
this launcher is great

i want to request you for a feature for 4gb patch
like we have Fov please add 4gb patch also

**Comment by namreeb** [comment]
This is a good idea, but I'm not sure I'm going to do it.  The launcher does not modify the exe file, and I suspect that it would have to in order to add `IMAGE_FILE_LARGE_ADDRESS_ AWARE` to the PE header.  According to https://devblogs.microsoft.com/oldnewthing/20170906-00/?p=96955 there is not a way to do this at runtime.
